// <auto-generated/>
/* *******************************
Generated for type: ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple`2
Generated on: 17/02/2025 08:46:45
Source assembly: BreeEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
******************************* */

using System;
using ProtoFlux.Core;
using Elements.Core;
using FrooxEngine;
using FrooxEngine.ProtoFlux;
using ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack;

namespace FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack
{
    
    [GenericTypes(GenericTypesAttribute.Group.EnginePrimitivesAndEnums)]
    
    [Category("ProtoFlux/Runtimes/Execution/Nodes/Tuples/Unpack")]
    public  partial class UnpackValueTuple<T0, T1> : global::FrooxEngine.ProtoFlux.Runtimes.Execution.VoidNode<global::FrooxEngine.ProtoFlux.FrooxEngineContext>
        
         where T0 : unmanaged where T1 : unmanaged
    {
        public override Type NodeType => typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<T0, T1>);

        

        
public global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<T0, T1> TypedNodeInstance { get; private set;}
public override INode NodeInstance => TypedNodeInstance;

public override N Instantiate<N>()
{
                if(TypedNodeInstance != null)
                    throw new InvalidOperationException("Node has already been instantiated");

                var node = new global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<T0, T1>();

                TypedNodeInstance = node;

                OnInstantiated();

                return node as N;
}

partial void OnInstantiated();

protected override void AssociateInstanceInternal(INode node)
{
    if(node is global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<T0, T1> typedNode)
    {
        TypedNodeInstance = typedNode;

        OnInstantiated();
    }
    else
        throw new ArgumentException("Node instance is not of type " + typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<T0, T1>));
}

public override void ClearInstance() => TypedNodeInstance = null;


        
        
        

        public override int NodeInputCount => base.NodeInputCount + 1;
        

        public override int NodeOutputCount => base.NodeOutputCount + 2;
        

        
        

        
        

        

        
        

             protected override ISyncRef GetInputInternal(ref int index)
        {
            var @base = base.GetInputInternal(ref index);

            if(@base != null)
                return @base;

            switch(index)
            {
                case 0: return Tuple;

                default:
                    index -= 1;
                    return null;
            };
        }

             protected override INodeOutput GetOutputInternal(ref int index)
        {
            var @base = base.GetOutputInternal(ref index);

            if(@base != null)
                return @base;

            switch(index)
            {
                case 0: return Value0;
case 1: return Value1;

                default:
                    index -= 2;
                    return null;
            };
        }

        
        

        

        
        
        
        

        
        

        public override string NodeName => "Unpack Tuple";


		public readonly SyncRef<global::FrooxEngine.ProtoFlux.INodeValueOutput<global::System.ValueTuple<T0, T1>>> Tuple;
		public readonly global::FrooxEngine.ProtoFlux.NodeValueOutput<T0> Value0;
		public readonly global::FrooxEngine.ProtoFlux.NodeValueOutput<T1> Value1;

    }
}
