
// <auto-generated/>
using Elements.Core;
using FrooxEngine;
using FrooxEngine.ProtoFlux;
using FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack;

namespace BreeEngine.ProtoFluxBindings;

public static partial class ProtoFluxMapper
{
	public static void Initialize()
	{
		RegisterBindingMappings();
	}

	static void RegisterBindingMappings()
	{
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Unpack.UnpackValueTuple<,,,,,,>));

		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,,,>));
		ProtoFluxHelper.RegisterBinding(typeof(global::ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,,,,>), typeof(global::FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.Bree.Tuples.Pack.PackValueTuple<,,,,,,>));
	}
}

